[CmdletBinding()]
param(
    [ValidateSet("all", "android", "iOS", "macOS", "windows10", "windows10X")]
    [string]$Platform = "all",

    [string]$Search,

    [switch]$IncludeSettings,

    [string]$ExportJsonPath,

    [string]$ExportMarkdownPath
)

<#
.SYNOPSIS
    Lightweight explorer for Intune Settings Catalog (deviceManagementConfigurationPolicy).

.DESCRIPTION
    Uses Microsoft Graph beta endpoint:
      - GET /beta/deviceManagement/configurationPolicies
      - GET /beta/deviceManagement/configurationPolicies/{id}/settings

    Requires Graph permission:
      - DeviceManagementConfiguration.Read.All (or ReadWrite for later automation).

.EXAMPLE
    # List all Windows 10+ Settings Catalog policies with 'BitLocker' in the name or description
    .\Get-CeIntuneSettingsCatalog.ps1 -Platform windows10 -Search BitLocker

.EXAMPLE
    # Export all macOS policies and their settings to JSON and a Markdown index
    .\Get-CeIntuneSettingsCatalog.ps1 -Platform macOS -IncludeSettings `
        -ExportJsonPath ./settings-catalog/raw `
        -ExportMarkdownPath ./settings-catalog/docs/index.md
#>

Write-Host "Querying Intune Settings Catalog policies from Graph (beta)..." -ForegroundColor Cyan

$baseUri = "https://graph.microsoft.com/beta/deviceManagement/configurationPolicies?`$top=100"
$policies = @()
$uri = $baseUri

do {
    $response = Invoke-MgGraphRequest -Method GET -Uri $uri
    if ($response.value) {
        $policies += $response.value
    }
    $uri = $response.'@odata.nextLink'
} while ($uri)

if ($Platform -ne "all") {
    $policies = $policies | Where-Object { $_.platforms -eq $Platform }
}

if ($Search) {
    $policies = $policies | Where-Object {
        ($_.name -like "*$Search*") -or
        ($_.description -like "*$Search*")
    }
}

if ($IncludeSettings) {
    Write-Host "Fetching settings for $($policies.Count) policies..." -ForegroundColor Yellow
    foreach ($policy in $policies) {
        $settingsUri = "https://graph.microsoft.com/beta/deviceManagement/configurationPolicies/$($policy.id)/settings"
        $settingsResponse = Invoke-MgGraphRequest -Method GET -Uri $settingsUri
        $policy | Add-Member -NotePropertyName "settings" -NotePropertyValue $settingsResponse.value -Force
    }
}

# Console output
$policies |
    Select-Object `
        id,
        name,
        description,
        platforms,
        technologies,
        settingCount,
        @{ Name = "Template"; Expression = { $_.templateReference.templateDisplayName } } |
    Sort-Object platforms, name |
    Format-Table -AutoSize

# JSON export
if ($ExportJsonPath) {
    $ExportJsonPath = (Resolve-Path -LiteralPath $ExportJsonPath -ErrorAction SilentlyContinue) ?? $ExportJsonPath
    if (-not (Test-Path $ExportJsonPath)) {
        New-Item -ItemType Directory -Path $ExportJsonPath -Force | Out-Null
    }

    foreach ($policy in $policies) {
        $safeName = ($policy.name -replace '[^\w\-]', '_')
        $fileName = "$($policy.platforms)_$safeName.json"
        $outPath  = Join-Path $ExportJsonPath $fileName

        $policy | ConvertTo-Json -Depth 20 | Out-File -FilePath $outPath -Encoding UTF8
    }

    Write-Host "Exported JSON policies to $ExportJsonPath" -ForegroundColor Green
}

# Markdown export
if ($ExportMarkdownPath) {
    $mdDir = Split-Path -Parent $ExportMarkdownPath
    if (-not (Test-Path $mdDir)) {
        New-Item -ItemType Directory -Path $mdDir -Force | Out-Null
    }

    $md = @()
    $md += "# Intune Settings Catalog export"
    $md += ""
    $md += "> Generated by Get-CeIntuneSettingsCatalog.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")"
    $md += ""

    foreach ($policy in $policies | Sort-Object platforms, name) {
        $md += $"## {0} ({1})" -f $policy.name, $policy.id
        $md += ""
        $md += "- **Platform:** $($policy.platforms)"
        $md += "- **Technologies:** $($policy.technologies)"
        $md += "- **Template:** $($policy.templateReference.templateDisplayName)"
        $md += "- **Settings:** $($policy.settingCount)"
        $md += ""
        if ($policy.description) {
            $md += "Description: $($policy.description)"
            $md += ""
        }
    }

    $md -join "`n" | Out-File -FilePath $ExportMarkdownPath -Encoding UTF8
    Write-Host "Exported Markdown index to $ExportMarkdownPath" -ForegroundColor Green
}